# program to demonstrate dictionary datatype
contacts= {'bill': '353-1234','rich': '269-1234', 'jane': '352-1234'}
print('Element in dictionary')
print (contacts)
print('value of bill and rich')
print (contacts['bill'])
print (contacts.get('rich'))
contacts['bill']='123-4567'
contacts['mick']='353-1234'
print('updated dictionary')
print (contacts)
print('length is')
print (len(contacts))
x=contacts.copy()
print('after copying')
print(x)
x.clear()
print('after clearing')
print(x)
contacts.pop('mick')
contacts.update({'bill':'353-1234'})
print('after popping and updating')
print(contacts)
print('items in dictionary')
print(contacts.items())
print('keys in dictionary')
print(contacts.keys())
print('values in dictionary')
print(contacts.values())
